pro/pro/app/urls.py
from django.conf.urls import url
from . import views
import django_cas_ng

app_name = 'app'
urlpatterns = [
    url(r'^$', views.index, name='index'),

	## Edit team ##
	# url(r'^(?P<u_id>[0-9]+)/add/$', views.addTeam, name='add'),
	#Order matters here for reason look into url for django
	url(r'^(?P<uid>[0-9]+)/(?P<option>.*)/edited/$', views.editTeam, name='edit'),
	url(r'^(?P<uid>[0-9]+)/(?P<option>.*)/$', views.showEmployees, name='show'),

	## SSO ##
    url(r'^accounts/login$', django_cas_ng.views.login, name='cas_ng_login'),
    url(r'^accounts/logout$', django_cas_ng.views.logout, name='cas_ng_logout'),
    url(r'^accounts/callback$', django_cas_ng.views.callback, name='cas_ng_proxy_callback'),
]

pro/pro/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django_cas_ng

urlpatterns = [
    url(r'^', include('pro.app.urls')),
    url(r'^admin/', admin.site.urls),

]

pro/pro/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals

class Employee(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	boss = models.ForeignKey('Coach', blank=True, null=True, on_delete=models.CASCADE)

	position = models.CharField(max_length=100, blank=True, null=True)
	department = models.CharField(max_length=100, blank=True, null=True)
	phone_number = models.CharField(max_length=10, blank=True, null=True)

	#def __str__(self):
	#	return '%s %s' % (self.user.first_name, self.user.last_name)

	def create_coach(self):
		c = Coach(employee_ptr_id = self.pk)
		c.__dict__.update(self.__dict__)
		c.save()
		return c

	# Simply doing .delete() deletes the employee as well
	def delete_coach(self):
		coach_ptr = DelCoach.objects.get(pk=self.pk)
		coach_ptr.delete()
		return self

def create_employee(sender, instance, created, **kwargs):
    Employee.objects.get_or_create(user=instance)

signals.post_save.connect(create_employee, sender=User, weak=False, dispatch_uid='create_employee')

class Approver(Employee):
	pass
	#def __str__(self):
	#	return self.employee_ptr.__str__()

class ApproverCoach(models.Model):
	approver = models.ForeignKey(Approver, on_delete=models.CASCADE)
	coach = models.ForeignKey('Coach', on_delete=models.CASCADE)

	def next_sequence_order(self):
		#not incrementing cause we can use 0 index
		return ApproverCoach.objects.filter(coach=self.coach).count()

	sequence_order = models.IntegerField(default=next_sequence_order)

	#add default ordering to this model
	#class Meta:
	#	ordering = ['sequence_order']

class Coach(Employee):
	approvers = models.ManyToManyField(Approver, through=ApproverCoach, related_name='coaches')
	#employee_ptr = models.OneToOneField('Employee', parent_link=True, related_name="%(app_label)s_%(class)s_related")

	def get_num_employees():
		return self.employee_set.count()

	#def __str__(self):
		#	return self.employee_ptr.__str__()

	class Meta:
		verbose_name_plural = 'coaches'

# So you can unmake an employee a coach
class DelCoach(models.Model):
	employee_ptr = models.PositiveIntegerField(db_column="employee_ptr_id", primary_key=True)
	class Meta:
		app_label = Coach._meta.app_label
		db_table = Coach._meta.db_table
		managed = False
	
class BaseForm(models.Model):
	submitted = models.BooleanField(default=False)
	submitted_date = models.DateTimeField(blank=True, null=True, default=None)

	#add created
	class Meta:
		abstract = True

class SelfEvaluation(BaseForm):
	pass

class PerformanceReview(BaseForm):
	pass

class Feedback360(BaseForm):
	provider = models.ForeignKey(Employee)

class CaseStatus(models.Model):
	#look into django fixtures, in progress, submitted, rejected
	status = models.CharField(max_length=100, blank=False, null=False)

class Case(models.Model):
	#people
	employee = models.ForeignKey(Employee)
	coach = models.ForeignKey(Coach, related_name='cases')

	#forms
	self_evaluation_form = models.OneToOneField(SelfEvaluation, related_name='cases')
	performance_review = models.OneToOneField(PerformanceReview, related_name='cases')

	feedback_360_forms = models.ForeignKey(Feedback360, related_name='cases')

	#status
	status = models.ForeignKey(CaseStatus)

pro/pro/app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django_cas_ng import views as baseviews
from django.views.decorators.csrf import csrf_exempt
from pro.app.models import Case, Employee, Coach
from django.views import generic

def index(request):
    if request.user.employee.coach:
        cases = Case.objects.filter(coach=request.user.employee)
    return render(request, 'index.html', {
        'employee': request.user.employee,
        'open_cases': cases, 
    })

def addTeam(request, u_id):
	coach = Coach.objects.get(user_id=u_id)
	added = False
	if not request.method == 'POST':
		employee_list = Employee.objects.all()
		employee_list = list(filter((lambda x: 
										not x in coach.employee_set.all() and x != coach.employee_ptr)
									, employee_list))
		return render(request, 'team.html', {
			'coach' : coach,
			'employee_list': employee_list,
			'added': added
		})
	new_employees = request.POST.getlist('employee')
	for employee in new_employees: 
		print(employee)
		coach.employee_set.add(Employee.objects.get(user_id=employee))
	coach.save()
	print(coach.employee_set.all())
	added = True
	return render(request, 'team.html', {
		'added': added
		})
		
def showEmployees(request, uid, option):
	coach = Coach.objects.get(user_id = uid)
	employee_list = Employee.objects.all()
	if option == "remove":
		employee_list = coach.employee_set.all()
	elif option == "add": 
		employee_list = list(filter((lambda x: 
										not x in coach.employee_set.all() and x != coach.employee_ptr), Employee.objects.all()))
	else:
		employee_list = Employee.objects.all()
	return render(request, 'employees.html', {
		'coach' : coach,
		'employee_list': employee_list,
		'option': option
	})

def editTeam(request, uid, option):
	selected = request.POST.getlist('employee')
	coach = Coach.objects.get(user_id = uid)
	if option == "add":
		for employee in selected: 
			coach.employee_set.add(Employee.objects.get(user_id=employee))
	else:
		for employee in selected:
			coach.employee_set.remove(Employee.objects.get(user_id=employee))
	coach.save()
	return render(request, 'employees.html', {
		'coach': coach,
		'employee_list': coach.employee_set.all(),
		'option': "all"
	})
	
	

pro/pro/app/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Flipp Pro</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static "semantic/dist/semantic.css" %}">
  <link rel="stylesheet" href="{% static "dist/css/styles.css" %}">


  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="{{ STATIC_URL }}images/favicon.png">

</head>
<body>
  <header>
    <div class="ui container">
      <div class="ui menu">
        <a class="item">
          <img src="{% static 'images/flipp-logo.png' %}">PRO
        </a>
        <!--
        <a class="item">Features</a>
        <a class="item">Testimonials</a>
        -->
        <div class="right menu">
          <a href="#" class="item">Logout</a>
        </div>
      </div>
    </div>
  </header>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="ui main container">
    {% block content %}
    {% endblock %}
  </div>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>

  <script src="{% static "semantic/dist/semantic.min.js" %}"
</html>

pro/pro/app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="ui vertical segment">
  <h1 class="ui header">Welcome {{ user.first_name }}! {% if employee.coach %}<div class="ui blue horizontal label">Coach</div>{% endif %}</h1>

  {% if employee.coach %}
  <a href="#" class="ui button">Start a Case</a>
  <a href="{% url 'app:show' employee.user_id "add" %}" class="ui button">Add Team Member</a>
  <a href="{% url 'app:show' employee.user_id "remove" %}" class="ui button">Remove Team Member</a>
  {% endif %}

</div>

<div class="ui vertical segment">
  <h2 class="ui header">Open Cases</h4>

  <div class="ui link cards">
  {% for case in open_cases %}
  <div class="ui card">
    <div class="image">
      {% if case.employee.user.first_name == 'Vinit' %}
      <img src="https://s3.amazonaws.com/f.wishabi.ca/creative/internal-directory/vinit.png">
      {% endif %}
      {% if case.employee.user.first_name == 'Leon' %}
      <img src="https://s3.amazonaws.com/f.wishabi.ca/creative/internal-directory/leon.png">
      {% endif %}
      {% if case.employee.user.first_name == 'Susan' %}
      <img src="https://s3.amazonaws.com/f.wishabi.ca/creative/internal-directory/susan.png">
      {% endif %}
    </div>
    <div class="content">
      <a class="header">{{ case.employee }}</a>
      <div class="meta">
        <span class="date">Associate QA Analyst</span>
      </div>
    </div>
    <div class="extra content">
      <a href="#">Write Performance Review</a></br>
      <a href="#">View Self Evaluation</a></br>
      <a href="#">View 360 Feedback</a></br>

      <button class="ui fluid button disabled">Submit for approval</button>
    </div>
  </div>
  {% endfor %}
  </div>
</div>

{% endblock %}